### ISSUE TITLE
Only the ribery command is working

### ISSUE THREAD

**Issue by Greeff** [applidium/zizou#2]
I have finally managed to get the app working following the deploy to heroku button (To a free heroku instance) and my slack (also a free account). I was looking to test this out before getting money thrown at it. 

So I followed all the readme instructions also adding `/bot` to the url in slack which points at my heroku app. 

The trigger word I have used is `fifa` 

So when I send `fifa ribery` I get a random French quote
However when I send say `fifa addteam BAR 99 99 99` the bot returns a list of possible commands. (which includes addteam). 
This is the same for all the other commands listed. 

Log info from Heroku:
```
2017-02-15T17:29:05.076552+00:00 heroku[router]: at=info method=POST path="/bot" host=<blanked for privacy>.herokuapp.com request_id=b419d3a5-66ee-4d3e-af61-9924659efcd7 fwd="<blanked for privacy>" dyno=web.1 connect=1ms service=78ms status=200 bytes=917
2017-02-15T17:29:20.724534+00:00 heroku[router]: at=info method=POST path="/bot" host=<blanked for privacy>.herokuapp.com request_id=507430cd-0d36-418f-83d6-e64083607d2b fwd="<blanked for privacy>" dyno=web.1 connect=0ms service=16ms status=200 bytes=544
```

**Comment by Hugo-Hache** [comment]
Hello @Greeff,

First sorry for the crazy delay. The deploy button on Heroku does create an application with the zizou code, but it does not setup the required database. Did you handle this database part ? I appreciate your feedback as it will help building a better README 👍

**Comment by Greeff** [comment]
Morning @Hugo-Hache 

Yeah you could be onto something there. When I get a spare few moments again I will try again. I cannot fully remember if I did the db part successfully or not. I know I did try lol.

**Comment by Hugo-Hache** [comment]
Based on your feedback I enhanced our Heroku deploy button 678f56247320bcf857636a49bbdd79c2ad004000 and it now automatically adds a database and run the migration script. If you deploy a fresh app with this button it should now work without issue, thanks @Greeff !

**Comment by Greeff** [comment]
Oh Sweet. Cheers @Hugo-Hache nice one.

**Comment by Greeff** [comment]
That has worked a charm.
